// Generated by gencpp from file navigation/Calibration.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_CALIBRATION_H
#define NAVIGATION_MESSAGE_CALIBRATION_H

#include <ros/service_traits.h>


#include <navigation/CalibrationRequest.h>
#include <navigation/CalibrationResponse.h>


namespace navigation
{

struct Calibration
{

typedef CalibrationRequest Request;
typedef CalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calibration
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::Calibration > {
  static const char* value()
  {
    return "a255970bffa18c4d56f14a3df609a6be";
  }

  static const char* value(const ::navigation::Calibration&) { return value(); }
};

template<>
struct DataType< ::navigation::Calibration > {
  static const char* value()
  {
    return "navigation/Calibration";
  }

  static const char* value(const ::navigation::Calibration&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::CalibrationRequest> should match
// service_traits::MD5Sum< ::navigation::Calibration >
template<>
struct MD5Sum< ::navigation::CalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Calibration >::value();
  }
  static const char* value(const ::navigation::CalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::CalibrationRequest> should match
// service_traits::DataType< ::navigation::Calibration >
template<>
struct DataType< ::navigation::CalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::Calibration >::value();
  }
  static const char* value(const ::navigation::CalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::CalibrationResponse> should match
// service_traits::MD5Sum< ::navigation::Calibration >
template<>
struct MD5Sum< ::navigation::CalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::Calibration >::value();
  }
  static const char* value(const ::navigation::CalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::CalibrationResponse> should match
// service_traits::DataType< ::navigation::Calibration >
template<>
struct DataType< ::navigation::CalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::Calibration >::value();
  }
  static const char* value(const ::navigation::CalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_CALIBRATION_H
