// Generated by gencpp from file navigation/CalibrationResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_CALIBRATIONRESPONSE_H
#define NAVIGATION_MESSAGE_CALIBRATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace navigation
{
template <class ContainerAllocator>
struct CalibrationResponse_
{
  typedef CalibrationResponse_<ContainerAllocator> Type;

  CalibrationResponse_()
    : answer()  {
    }
  CalibrationResponse_(const ContainerAllocator& _alloc)
    : answer(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::navigation::CalibrationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::CalibrationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrationResponse_

typedef ::navigation::CalibrationResponse_<std::allocator<void> > CalibrationResponse;

typedef boost::shared_ptr< ::navigation::CalibrationResponse > CalibrationResponsePtr;
typedef boost::shared_ptr< ::navigation::CalibrationResponse const> CalibrationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::CalibrationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::CalibrationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::CalibrationResponse_<ContainerAllocator1> & lhs, const ::navigation::CalibrationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::CalibrationResponse_<ContainerAllocator1> & lhs, const ::navigation::CalibrationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::CalibrationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::CalibrationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CalibrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CalibrationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CalibrationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CalibrationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a255970bffa18c4d56f14a3df609a6be";
  }

  static const char* value(const ::navigation::CalibrationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa255970bffa18c4dULL;
  static const uint64_t static_value2 = 0x56f14a3df609a6beULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/CalibrationResponse";
  }

  static const char* value(const ::navigation::CalibrationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::CalibrationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String answer\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::navigation::CalibrationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::CalibrationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::CalibrationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::CalibrationResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_CALIBRATIONRESPONSE_H
