// Generated by gencpp from file navigation/CalibrationRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_CALIBRATIONREQUEST_H
#define NAVIGATION_MESSAGE_CALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct CalibrationRequest_
{
  typedef CalibrationRequest_<ContainerAllocator> Type;

  CalibrationRequest_()
    {
    }
  CalibrationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::navigation::CalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::CalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalibrationRequest_

typedef ::navigation::CalibrationRequest_<std::allocator<void> > CalibrationRequest;

typedef boost::shared_ptr< ::navigation::CalibrationRequest > CalibrationRequestPtr;
typedef boost::shared_ptr< ::navigation::CalibrationRequest const> CalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::CalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::CalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navigation::CalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::CalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::CalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::CalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::CalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::navigation::CalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::CalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/CalibrationRequest";
  }

  static const char* value(const ::navigation::CalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::CalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::navigation::CalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::CalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::CalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::navigation::CalibrationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_CALIBRATIONREQUEST_H
